apiVersion: cert-manager.io/v2
kind: Certificate
metadata:
  name: localhost-cert
  namespace: istio-ingress
spec:
  secretName: localhost-tls
  issuerRef:
    name: staging-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: localhost
  dnsNames:
    - localhost
